language: python
python:
  - 3.6
services:
  - postgresql
env:
  global:
  - DATABASE_URL=postgres://postgres@localhost/hbeers
  - SSL_REDIRECT=0
  - secure: aIt3vS/XxeW0Ymv+Sq1GxFB8SrvtXSAk/JidJ+95nRdNAsdIZNX403nG2Q9cG+hDF+o3zq2FA0RBoIhvOQrN1NrUdOaDbenc5KpNy67qz7hFwWMbwDTJf+0maJH2vbNRn7WYVaEIeU1gj7dx/hKTreNkCyRdw3AGcau0zrzFcTWD4L/4V4Oqwirv5xFlB8xbt6XNAXuVPKHiQJvUQw6l6k0X0WVXmSh0SMXdPgt9DtvfNZvSVNznrd2Fkzep0VpnjWZhYweLmjrqqQInmskXpJF0Hn5ngmn0lQlsfxEa+7TyK2psZsQfrwnj7MEq0kxqh417iY1bNRevBv3exiKzW6mWkUlIop10Nmq1bzLgpZnJQb3tq56KixCXfSaEQKwDlP2cm70UBaJXnIlY2crTBjlJ4KpGDmGf5IDOiMNUcn6sAgK1JQLGJEcfhXRjGh5tcyHFR/Ft1bezmfbR6yenmOkxMZsrzDyuJdgB7dLwbqfgNeWnhU+D3OeDseqkwHqiCnELomqm4kesPck6LKQpGPJnyIKlO5HF4BKVhD6fUn/7OvfLEL5sYzT1JD8PLqeMvxiCRpbUlILHSJt5WDNpglb8IULg8bI0Me1lOe1krt7KWAMoY5Bc5cTYJIPaqoap1FT8qagbKNeAEnsq+ITI24YzqJA/oK5cXKiT4oGvA48=
before_script: 
  - psql -c 'create database hbeers;' -U postgres
script: python manage.py test
